Fix failing spec due to leaking watched paths
Error: Leaking subscriptions for paths:
	/Users/edward/projects/markdown-preview-plus/spec/fixtures/
	subdir/file.markdown,
	/Users/edward/projects/markdown-preview-plus/spec/fixtures/
	subdir/image1.png

I beleive this is due to watching images for updates in the cache fix in
`lib/image-watch-helper.coffee` (which is why this is not failing in
markdown-preview).